# Generated by Django 5.0.4 on 2024-04-28 10:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="category", max_length=255, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=datetime.datetime(2024, 4, 28, 10, 32, 57, 819461),
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=datetime.datetime(2024, 4, 28, 10, 32, 57, 819481),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="workshop.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
                "ordering": ["title", "price", "description"],
            },
        ),
    ]
